Remove C99 flag
Removed c99 flag to fix below build error:
error: "BoringSSL must be built in C11 mode or higher."

As per commit in external/boringssl:
"Try to require C11 (in non-MSVC compilers).
Update-Note: If the build fails with an error about C11,
remove -std=c99 or -std=gnu99 from your build.
Refcounting will get faster"

Signed-off-by: svenate <salini.venate@intel.com>